DATA_FOLDER: inputs
RESULTS_FOLDER: output
REFERENCE_WIND_TURBINE: IEA-15-240-RWT
BLADE_DEFINITION_INPUT_FILE: IEA-15-240-RWT_AeroDyn15_blade.dat
OPERATIONAL_CONDITIONS_FILE: IEA_15MW_RWT_Onshore.opt
AIRFOIL_DATA_FOLDER: airfoils

AIRFOIL_SHAPE_IDENTIFIER: _Coords
AIRFOIL_INFO_IDENTIFIER: _Polar
# Vars for the script

#Define global constant parameters

RADIUS: 120
AIR_DENSITY: 1.225
NUMBER_BLADES: 3
TOLERANCE: 1e-8
MAX_ITER: 1000
RATED_POWER: 15000000      # W
CORRECTION_FACTOR: 0.1    # Relaxation factor for induction updates
EPSILON: 1e-6              # Small value to avoid division by zero
