DATA_FOLDER: inputs
RESULTS_FOLDER: output
REFERENCE_WIND_TURBINE: IEA-15-240-RWT
BLADE_DEFINITION_FILE: IEA-15-240-RWT_AeroDyn15_blade.dat
OPERATIONAL_CONDITIONS_FILE: IEA_15MW_RWT_Onshore.opt
AIRFOIL_DATA_FOLDER: airfoils

# Vars for the script
